/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_angusj_clipper_Clipper */

#ifndef _Included_com_angusj_clipper_Clipper
#define _Included_com_angusj_clipper_Clipper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_angusj_clipper_Clipper
 * Method:    generatePath
 * Signature: ([[DD)[[D
 */
JNIEXPORT jobjectArray JNICALL Java_com_angusj_clipper_Clipper_generatePath
  (JNIEnv *, jobject, jobjectArray, jdouble);

#ifdef __cplusplus
}
#endif
#endif
